### ISSUE TITLE
Taskana Adapter db configuration issue

### ISSUE THREAD

**Issue by Jasphy** [Taskana/taskana#1632]
To connect to Taskana  I have added ( taskana-adapter-taskana-connector ) in the Flowable BPMN (https://flowable.com/open-source/docs/bpmn/ch02-GettingStarted/) spring boot project  pom xml

By default flowable creates few tables like Taskana , When I added the adapter connector dependency tables are not creating ,  I am getting below error  and failing to start the application

When I remove taskana-adapter-taskana-connector dependency , it works fine 

Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: relation "act_re_deployment" does not exist
  Position: 34
### The error may exist in org/flowable/db/mapping/entity/Deployment.xml

Can you please help me how to integrate Flowable BPMN with Taskana

**Comment by holgerhagen** [comment]
Hi Jasphy,
I'm afraid that we do not support Flowable at the moment. Can you tell us more about your use case?

"act_re_deployment" is not a TASKANA table. Therefore it is hard to tell what is going wrong here. 
Regards
Holger

**Comment by Jasphy** [comment]
Hi Holger ,

Thanks for your reply.

Its schema issue , flowable tables are looking up in taskana schema , Able to fix it now 

I am checking out tasakana adapter flow.
