### ISSUE TITLE
GitHub Actions: new way to print to stdout

### ISSUE THREAD

**Issue by arolfes** [Taskana/taskana#2139]
Currently our Workflow throws this warning:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

We have to adjust the way we write to stdout in order to fix that warning.

**Comment by ryzheboka** [comment]
Hi @arolfes , where can I find the warning? I didn't find it. Is it sill relevant?

**Comment by arolfes** [comment]
Hi @ryzheboka ,
the warning came up when the echo command was executed.
you are right, it is currently not showiing up anymore. Looks like github changed something and the users are not affected.
I close this Bug.
