### ISSUE TITLE
Adjust HistoryCleanupJob for new end state history events

### ISSUE THREAD

**Issue by arolfes** [Taskana/taskana#2143]
With TSK-1333  introduced new history events for the task end states terminated and cancelled. The HistoryCleanupJob must be adjusted for these events.

**Comment by jamesrdi** [comment]
@arolfes I want to ask you, in what way should the historyCleanupJob be adjusted for the terminated and cancelled events? Currently the terminated and cancelled task are also cleaned in the job

**Comment by ryzheboka** [comment]
We can't reproduce the issue. It looks like it was already done by #1173

**Comment by ryzheboka** [comment]
We can't reproduce the issue. It looks like it was already done by #1173

**Comment by ryzheboka** [comment]
We can't reproduce the issue. It looks like it was already done by #1173
