### ISSUE TITLE
Surround NotAuthorizedException with try catch in the force-methods of TaskService

### ISSUE THREAD

**Issue by arolfes** [Taskana/taskana#2162]
At the moment, NotAuthorizedException is in the method signature of force methods in TaskService. However, it should not be thrown there. Please surround the corresponding code with try .. catch like in the picture (but without :D).

![forceMethodsRewriteNewTicket](https://user-images.githubusercontent.com/2970074/226538211-74cee0c2-c3b9-4158-8c93-2865e53e0ca3.jpg)

**Comment by Lnrivas** [comment]
I am happy to work on this as my first issue. Not sure how to mark it as "in progress" on the kanban board, but I will create a pull request with my changes when done.

**Comment by mustaphazorgati** [comment]
> I am happy to work on this as my first issue. Not sure how to mark it as "in progress" on the kanban board, but I will create a pull request with my changes when done.

I have moved this to "Review" and already reviewed your PR. Thanks again for your contribution :heart:!

If you're interested: This issue can be expanded a little bit. If you want I can create a follow-up Issue for you.

**Comment by mustaphazorgati** [comment]
> At the moment, NotAuthorizedException is in the method signature of force methods in TaskService. However, it should not be thrown there. Please surround the corresponding code with try .. catch like in the picture (but without :D).
> 
> ![forceMethodsRewriteNewTicket](https://user-images.githubusercontent.com/2970074/226538211-74cee0c2-c3b9-4158-8c93-2865e53e0ca3.jpg)
Image is wrong: For the method forceCancelClaim it should be the `InvalidOwnerException` which is unnecessary
