### ISSUE TITLE
Reuse Basequery#toLowerCopy

### ISSUE THREAD

**Issue by arolfes** [Taskana/taskana#2172]
The `TimeIntervalReportBuilderImpl` and the `WorkbasketPriorityReportBuilderImpl` define a `toLowerCopy` method, which is an exact duplicate of `BaseQuery#toLowerCopy`. Please refactor this by either introducing a util class or making `BaseQuery#toLowerCopy` static.

**Comment by ryzheboka** [comment]
Done in #2278
