### ISSUE TITLE
No Master Domain in Admin UI

### ISSUE THREAD

**Issue by gitgoodjhe** [Taskana/taskana#2201]
The Master Domain is not shown in the TASKANA Admin UI.

Before TASKANA 6.0 there was a workaround: Configuring an "empty" domain like this:

taskana.domains=DOMAIN1, ,DOMAIN2,DOMAIN3

This seems to not be possible anymore with the new | delimiters

**Comment by arolfes** [comment]
To be more precise:

the visibility of master domain is depend from the customer installation. Therefore it should be possible to switch it off.

The visibility of master domain should be different then the other "configured" domains

**Comment by arolfes** [comment]
Hi @gitgoodjhe,

how urgent is this change/bugfix for you?

Which solution do you prefere? Ugly in the UI or properly in the backend with a release?

**Comment by gitgoodjhe** [comment]
Hi @arolfes let's talk about this in our upcoming sync call

**Comment by arolfes** [comment]
We decided to always add the master domain to the configuration as empty string at last position of configured domains.

therefore we switch from Set to List, because its sorted
and add an empty string to last position of domains list

also we agreed to switch classificationTypes from Set to List
