### ISSUE TITLE
TaskCleanupJobAccTest has a flaky test

### ISSUE THREAD

**Issue by ryzheboka** [Taskana/taskana#2222]
The should_SetNextScheduledJobBasedOnDueDateOfPredecessor_When_RunningTaskCleanupJob test in TaskCleanupJobAccTest sometimes fails in the Pipeline. However, rerunning jobs usually helps.
Example error message:
java.lang.AssertionError: 
Expecting actual:
  [2023-04-12T08:46:40.825Z]
to contain exactly (and in same order):
  [2023-04-13T08:46:40.825Z]
but some elements were not found:
  [2023-04-13T08:46:40.825Z]
and others were not expected:
  [2023-04-12T08:46:40.825Z]

**Comment by mustaphazorgati** [comment]
Just a thought: Is this issue related to the nanosecond truncing? Maybe worth a shot

**Comment by arolfes** [comment]
Hello @ryzheboka ,
maybe we should refactore the test to use the _new_ test-api
and see if the error still occurs
What do you think?

**Comment by ryzheboka** [comment]
Hello @arolfes ,
it sounds like a good idea! Especially because some other test cases in this class (e. g. should_DeleteOldTaskCleanupJobs_When_InitializingSchedule) seem to be flaky as well.

**Comment by arolfes** [comment]
Hi @ryzheboka , @mustaphazorgati ,

with using new TestApi the flaky tests are gone. I run the pipeline 6 times and the error does not occur.

The PR is still draft, because we need to change the RunAsUser. Therefore I need an example from @mustaphazorgati . :-)
