### ISSUE TITLE
Type of classifications should have same order as defined in taskana.properties

### ISSUE THREAD

**Issue by arolfes** [Taskana/taskana#2226]
The Items in the `type` dropdown should have the same order as the items in taskana.properties

![Classification_Types_Dropdown](https://user-images.githubusercontent.com/2970074/233107229-e13e899f-7c64-43ba-94bc-2951b73eee4f.png)
![Classification_Types_Dropdown_open](https://user-images.githubusercontent.com/2970074/233107271-990ed98f-31b2-448a-a96e-f9d46e912511.png)

In the image above the ordering of the items is wrong, because the config is:
```properties
taskana.classification.types=TASK|DOCUMENT
```
and therefore `TASK` should be the first item and preselected

**Comment by ryzheboka** [comment]
#2339 is another issue for the same problem that is currently in review.

**Comment by ryzheboka** [comment]
#2339 is another issue for the same problem that is currently in review.

**Comment by ryzheboka** [comment]
#2339 is another issue for the same problem that is currently in review.
