### ISSUE TITLE
Write update scripts for adding new Permission READTASKS into the database schema 

### ISSUE THREAD

**Issue by ryzheboka** [Taskana/taskana#2240]
This issue is part of #2242. See there for more details.

Todos:
 - Write migration scrips for all databases. Migration scripts need to add the new column PERM_READTASKS and fill it with the same values as in the PERM_READ column.

**Comment by mustaphazorgati** [comment]
* What is the use for the "READTASKS" permission?
* Is the name "READTASKS" fix?
* Why are we excluding the Oracle DB?

**Comment by ryzheboka** [comment]
Sorry @mustaphazorgati, I mixed something up. It still needs to be implemented for Oracle DB. I added a detailed explaination for this issue in #2242
