### ISSUE TITLE
Commit Hooks won't work without JIRA Tickets

### ISSUE THREAD

**Issue by arolfes** [Taskana/taskana#2271]
The commit hooks relay on an existing Jira ticket number.
We don't use Jira anymore, so we need to change the commit hooks.

**Comment by arolfes** [comment]
Hello @mustaphazorgati ,

do you have an idea what to do here?

**Comment by mustaphazorgati** [comment]
> Hello @mustaphazorgati ,
> 
> do you have an idea what to do here?

Yes, we have to adjust our commit hooks in https://github.com/Taskana/taskana/tree/master/qa/hooks
