### ISSUE TITLE
Add a boolean flag which shows if a task has comments or not

### ISSUE THREAD

**Issue by gitgoodjhe** [Taskana/taskana#2290]
- extend the taskSummary and it's representationModel/Assembler with a new boolean attribute which shows if a task has comments or not
- extend TaskCommentMapper for retrieving taskComments from multiple taskIds
- extend the list() method of the TaskQuery to augment the list of tasks after the initial DB calls. Meaning set the new attribute for each task to true, if the task has comments and false if it doesn't. This is consistent with how other attributes are added like WorkbasketSummary or ClassificationSummary 
- make the augmentation a feature toggle via configuration property -> only augment the task list when the feature is activated

**Comment by ryzheboka** [comment]
@gitgoodjhe , what is the status of this issue? I would like to close it if's not relevant

**Comment by ryzheboka** [comment]
We already have another issue for this one (#2542 )
