### ISSUE TITLE
Default TimeIntervalColumnHeader Ranges are incorrect

### ISSUE THREAD

**Issue by gitgoodjhe** [Taskana/taskana#2310]
Currently the default ranges have an overlap, for example:

      new TimeIntervalColumnHeader.Range(Integer.MIN_VALUE, -10),
                new TimeIntervalColumnHeader.Range(-10, -5),

like this, a task with -10 will get counted twice because the ranges are inclusive

**Comment by nyuuyn** [comment]
Can we close this issue as it is released in 6.3.0 ?

**Comment by ryzheboka** [comment]
This is already released
