### ISSUE TITLE
Having this issue maven-installing taskana-common

### ISSUE THREAD

**Issue by sourav1768** [Taskana/taskana#2345]
Error(38, 19): Cannot infer type-variables T, K, U, T

**Comment by mustaphazorgati** [comment]
Which java version are you using? You need to use jdk11

**Comment by sourav1768** [comment]
@mustaphazorgati I'm using JDK 17(Java version 17.0.7), Maven version 3.6.3. Is there any workaround? Switching back to JDK 11 would require a lot of modules to be re-built. 

Thanks

**Comment by arolfes** [comment]
Hello @sourav1768 ,
last week we merged the JAVA_17 branch into the master and created a release.
https://github.com/Taskana/taskana/releases/tag/v7.0.0
Therefore I will close the ticket.
Please reopen the ticket if building taskana with jdk17 still causes problems.
Best Regards
