### ISSUE TITLE
demo app does not run because of JAVA11

### ISSUE THREAD

**Issue by arolfes** [Taskana/taskana#2434]

**Comment by arolfes** [comment]
must do:
extend the verification not only for rest docs it must also be checked if the login is possible after the deployment

**Comment by arolfes** [comment]
one more thing is needed
a local test if the login page is available

currently we struggling with thymeleaf

**Comment by ryzheboka** [comment]
Hi @Alex, this issue seems to be irrelevant after Spring Boot update. Is it still a bug? Or can we close it?

**Comment by arolfes** [comment]
Yes, its solved
